<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0-windows10.0.26100.0</TargetFramework>
    <LangVersion>14</LangVersion><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CodeAnalysisRuleSet></CodeAnalysisRuleSet>
    <NoWarn>$(NoWarn);MSB3884</NoWarn>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="11.0.0-preview.6.26359.118" />
    <PackageReference Include="JxlNet" Version="0.11.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TrueToneCap.Core\TrueToneCap.Core.csproj" />
  </ItemGroup>
</Project>
